In [15]:
import numpy as np
import random
import scipy.linalg as la

#arr = np.array([[random.randint(1, 100) for x in range(0, 10)] for y in range(0, 10)])
arr = np.array([[2,3,2,4],[4,10,-4,0],[-3,-2,-5,-2],[-2,4,4,-7]])
arr = arr.astype(float)
print(arr)


def lu(A):

    # Get the number of rows
    n = A.shape[0]

    U = A.copy()
    L = np.eye(n, dtype=np.double)

    # Loop over rows
    for i in range(n):

        # Eliminate entries below i with row operations
        # on U and reverse the row operations to
        # manipulate L
        factor = U[i + 1 :, i] / U[i, i]
        L[i + 1 :, i] = factor
        U[i + 1 :] -= factor[:, np.newaxis] * U[i]

    return L, U


def plu(A):

    # Get the number of rows
    n = A.shape[0]

    # Allocate space for P, L, and U
    U = A.copy()
    L = np.eye(n, dtype=np.double)
    P = np.eye(n, dtype=np.double)

    # Loop over rows
    for i in range(n):

        # Permute rows if needed
        for k in range(i, n):
            if ~np.isclose(U[i, i], 0.0):
                break
            U[[k, k + 1]] = U[[k + 1, k]]
            P[[k, k + 1]] = P[[k + 1, k]]

        # Eliminate entries below i with row
        # operations on U and #reverse the row
        # operations to manipulate L
        factor = U[i + 1 :, i] / U[i, i]
        L[i + 1 :, i] = factor
        U[i + 1 :] -= factor[:, np.newaxis] * U[i]

    return P, L, U


print(type(arr))
print(lu(arr))
print()
print(plu(arr))

[[ 2.  3.  2.  4.]
 [ 4. 10. -4.  0.]
 [-3. -2. -5. -2.]
 [-2.  4.  4. -7.]]
<class 'numpy.ndarray'>
(array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 2.        ,  1.        ,  0.        ,  0.        ],
       [-1.5       ,  0.625     ,  1.        ,  0.        ],
       [-1.        ,  1.75      ,  6.66666667,  1.        ]]), array([[  2.,   3.,   2.,   4.],
       [  0.,   4.,  -8.,  -8.],
       [  0.,   0.,   3.,   9.],
       [  0.,   0.,   0., -49.]]))

(array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]]), array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 2.        ,  1.        ,  0.        ,  0.        ],
       [-1.5       ,  0.625     ,  1.        ,  0.        ],
       [-1.        ,  1.75      ,  6.66666667,  1.        ]]), array([[  2.,   3.,   2.,   4.],
       [  0.,   4.,  -8.,  -8.],
       [  0.,   0.,   3.,   9.],
       [  0.,   0.,   0., -49.]]))
