In [22]:
import numpy as np
import random
import scipy.linalg as la

#arr = np.array([[random.randint(1, 100) for x in range(0, 10)] for y in range(0, 10)])
arr = np.array([[2,3,2,4],[4,10,-4,0],[-3,-2,-5,-2],[-2,4,4,-7]])
arr = arr.astype(float)
print(arr)



def lu(A):

    # Get the number of rows
    n = A.shape[0]

    U = A.copy()
    L = np.eye(n, dtype=np.double)

    # Loop over rows
    for i in range(n):

        # Eliminate entries below i with row operations
        # on U and reverse the row operations to
        # manipulate L
        factor = U[i + 1 :, i] / U[i, i]
        L[i + 1 :, i] = factor
        U[i + 1 :] -= factor[:, np.newaxis] * U[i]

    return L, U


def plu(A):

    # Get the number of rows
    n = A.shape[0]

    # Allocate space for P, L, and U
    U = A.copy()
    L = np.eye(n, dtype=np.double)
    P = np.eye(n, dtype=np.double)

    # Loop over rows
    for i in range(n):

        # Permute rows if needed
        for k in range(i, n):
            if ~np.isclose(U[i, i], 0.0):
                break
            U[[k, k + 1]] = U[[k + 1, k]]
            P[[k, k + 1]] = P[[k + 1, k]]

        # Eliminate entries below i with row
        # operations on U and #reverse the row
        # operations to manipulate L
        factor = U[i + 1 :, i] / U[i, i]
        L[i + 1 :, i] = factor
        U[i + 1 :] -= factor[:, np.newaxis] * U[i]

    return P, L, U


print(type(arr))
print(lu(arr))
print()
print(plu(arr))

[[ 2.  3.  2.  4.]
 [ 4. 10. -4.  0.]
 [-3. -2. -5. -2.]
 [-2.  4.  4. -7.]]
<class 'numpy.ndarray'>
(array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 2.        ,  1.        ,  0.        ,  0.        ],
       [-1.5       ,  0.625     ,  1.        ,  0.        ],
       [-1.        ,  1.75      ,  6.66666667,  1.        ]]), array([[  2.,   3.,   2.,   4.],
       [  0.,   4.,  -8.,  -8.],
       [  0.,   0.,   3.,   9.],
       [  0.,   0.,   0., -49.]]))

(array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]]), array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 2.        ,  1.        ,  0.        ,  0.        ],
       [-1.5       ,  0.625     ,  1.        ,  0.        ],
       [-1.        ,  1.75      ,  6.66666667,  1.        ]]), array([[  2.,   3.,   2.,   4.],
       [  0.,   4.,  -8.,  -8.],
       [  0.,   0.,   3.,   9.],
       [  0.,   0.,   0., -49.]]))


In [23]:
import numpy as np
import scipy as sp
import random

matrix = np.zeros(shape = (10,10))
print(matrix)

def matrixRand(matrix, num):
  for row in range(0,num):
    for col in range(0,num):
      matrix[row][col] = random.randint(0,100)

  return matrix    

matrix = matrixRand(matrix, 5)
print(matrix)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[18. 16. 48.  3. 84.  0.  0.  0.  0.  0.]
 [37.  3. 24. 41. 28.  0.  0.  0.  0.  0.]
 [68. 29. 23. 25. 45.  0.  0.  0.  0.  0.]
 [ 5. 71. 90. 20. 47.  0.  0.  0.  0.  0.]
 [32. 24. 63. 86. 72.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


In [57]:
def matrixCalc(matrix, num):
  matrixTMP = np.zeros(shape = (num, num))
  
  for row in range(0, num):
    for col in range(0, num):
      matrixTMP[row][col] = matrix[row][col]
      
  return matrixTMP

matrixReady = matrixCalc(matrix, 5)
print(matrixReady)

def LUCalc(matrix):
    U = np.zeros(shape=matrix.shape)
    L = np.eye(matrix.shape[0])

    matrixTMP = matrix
    matrixTMP = matrixTMP.astype(float)

    for j in range(0,matrix.shape[0]-1):
        for i in range(j + 1, matrix.shape[0]):
            if matrixTMP[i, j] != 0.0:
                mult = matrixTMP[i, j] / matrixTMP[j, j]
                matrixTMP[i, :] = matrixTMP[i, :] - mult * matrixTMP[j, :]
                L[i, j] = mult

    # U es A después de escalonar
    U = matrixTMP

    np.set_printoptions(suppress= True)

    return L, U


LUCalc(matrixReady)

[[18. 16. 48.  3. 84.]
 [37.  3. 24. 41. 28.]
 [68. 29. 23. 25. 45.]
 [ 5. 71. 90. 20. 47.]
 [32. 24. 63. 86. 72.]]
[[  18.           16.           48.            3.           84.        ]
 [   0.          -29.88888889  -74.66666667   34.83333333 -144.66666667]
 [   0.            0.          -79.78066914  -22.9795539  -120.13754647]
 [   0.           -0.            0.          122.53976982 -163.55039374]
 [   0.            0.            0.            0.           66.15755054]]
[[ 1.          0.          0.          0.          0.        ]
 [ 2.05555556  1.          0.          0.          0.        ]
 [ 3.77777778  1.05204461  1.          0.          0.        ]
 [ 0.27777778 -2.2267658   1.12306044  1.          0.        ]
 [ 1.77777778  0.14869888  0.14076697  0.64241798  1.        ]]
